# Generated by Django 3.1.3 on 2020-12-08 23:26

from django.db import migrations, models
import django.utils.timezone
import pollsplus.models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsplus', '0002_auto_20201207_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=pollsplus.models.user_path),
            preserve_default=False,
        ),
    ]
